Search stream
S3zh/twitch-app pull request #2
Opened 2018-09-13 10:04 UTC by S3zh

2018-09-14 12:29 UTC, e-tolpeko requested changes

2018-09-14 12:29 UTC, e-tolpeko commented on src/app/app-routing.module.ts
>    {path: '', redirectTo: '/games', pathMatch: 'full'},
этот роут в конец ставится

2018-09-14 12:29 UTC, e-tolpeko commented on src/app/app.component.css
> +mat-form-field {
добавь класс и сделай классовый селектор

2018-09-14 12:29 UTC, e-tolpeko commented on src/app/app.component.html
> +    <input matInput [(ngModel)]="inputValue" (keyup)="$event.keyCode == 13 ? searchInit() : null" placeholder="Search">
используй FormControl и в компоненте подписывайся на его valueChanges

2018-09-14 12:29 UTC, e-tolpeko commented on src/app/app.component.html
> +  <button mat-button routerLink="/search/{{inputValue}}" class="search-button" (click)="searchInit()" >Search</button>
сделай внутри геттер для ссылки. И еще не понятно, кнопка это ссылка? Для чего тогда на ней обработчик

2018-09-14 12:29 UTC, e-tolpeko commented on src/app/app.component.ts
> +  static checkSearchInit$ = new BehaviorSubject('');
статическая переменная тут не нужна

2018-09-14 12:29 UTC, e-tolpeko commented on src/app/app.component.ts
> +    this.router.navigate([`/search/${this.inputValue}`]);
Удали тогда в шаблоне ссылку

2018-09-14 12:29 UTC, e-tolpeko commented on src/app/search-stream/search-stream.component.css
> +h1{
везде должны быть классовые селекторы

2018-09-14 12:29 UTC, e-tolpeko commented on src/app/search-stream/search-stream.component.html
> +    <a routerLink="/stream/{{stream.channel.name}}">
тут геттер нужен

2018-09-14 12:29 UTC, e-tolpeko commented on src/app/search-stream/search-stream.component.html
> +        <mat-card-title>{{stream.channel.display_name}}</mat-card-title>
а для чего тут внутрь пробрасывать текст?

2018-09-14 12:29 UTC, e-tolpeko commented on src/app/search-stream/search-stream.component.html
> +      <img src="{{stream.preview.large}}">
для атрибутов используй квадратные скобки [src]="..."

2018-09-14 12:29 UTC, e-tolpeko commented on src/app/search-stream/search-stream.component.ts
>    styleUrls: ['./search-stream.component.css']
Везде должна быть стратегия OnPush

2018-09-14 12:29 UTC, e-tolpeko commented on src/app/search-stream/search-stream.component.ts
> +      .subscribe((query: string) => {
нету отписки

2018-09-14 12:29 UTC, e-tolpeko commented on src/app/search-stream/search-stream.component.ts
> +          this.isNotEmpty = false;
this.isNotEmpty = !!answer.length;

2018-09-17 11:00 UTC, S3zh commented on src/app/app.component.ts
> +  static checkSearchInit$ = new BehaviorSubject('');
а как обратиться к ней из другого компонента(StreamSearchComponent)?

2018-09-17 11:01 UTC, S3zh commented on src/app/search-stream/search-stream.component.html
> +        <mat-card-title>{{stream.channel.display_name}}</mat-card-title>
По названию потом создается запрос

2018-09-17 11:03 UTC, S3zh commented on src/app/app.component.html
> +  <button mat-button routerLink="/search/{{inputValue}}" class="search-button" (click)="searchInit()" >Search</button>
Все поменял, теперь поиск инициализируется по valueChanges

2018-09-17 11:08 UTC, e-tolpeko commented on src/app/app.component.ts
> +  static checkSearchInit$ = new BehaviorSubject('');
все взаимодействия должны строиться через сервис

2018-09-17 11:09 UTC, S3zh commented on src/app/app-routing.module.ts
>    {path: '', redirectTo: '/games', pathMatch: 'full'},
он уже последний, куда его нужно поставить?

2018-09-17 11:13 UTC, S3zh commented on src/app/search-stream/search-stream.component.ts
>    styleUrls: ['./search-stream.component.css']
Мне просто нужно добавить changeDetection: ChangeDetectionStrategy.OnPush?

2018-09-17 11:19 UTC, e-tolpeko requested changes

2018-09-17 11:19 UTC, e-tolpeko commented on src/app/app.component.html
> +    <input matInput [formControl]="inputValue" (keyup)="$event.keyCode == 13 ? searchInit() : null" placeholder="Search" >
(keyup)="$event.keyCode == 13 ? searchInit() : null"   больше не нужен

2018-09-17 11:19 UTC, e-tolpeko commented on src/app/app.component.ts
> +        debounceTime(500),
Добавь сюда filter , а ` if (!this.inputValue.value) {return; }` убери

2018-09-17 11:19 UTC, e-tolpeko commented on src/app/app.component.ts
> +    AppComponent.checkSearchInit$.next(this.inputValue.value);
Используй сервис для передачи данных

2018-09-17 11:19 UTC, e-tolpeko commented on src/app/app.module.ts
> +    ReactiveFormsModule,
В конце перечислений запятая не нужна

2018-09-17 11:25 UTC, e-tolpeko requested changes

2018-09-17 11:25 UTC, e-tolpeko commented on src/app/app.component.ts
>  })
стратегия должна быть OnPush

2018-09-17 11:25 UTC, e-tolpeko commented on src/app/search-stream/search-stream.component.ts
>    styleUrls: ['./search-stream.component.css']
И если есть запросы или асинхронные методы, правильно их обработать. https://alligator.io/angular/change-detection-strategy/

2018-09-17 11:28 UTC, e-tolpeko requested changes

2018-09-17 11:28 UTC, e-tolpeko commented on src/app/app-routing.module.ts
>    {path: '', redirectTo: '/games', pathMatch: 'full'},
` {path: '', redirectTo: '/games', pathMatch: 'full'},`  ставится в конец после этого ` {path: 'search/:query', component: SearchStreamComponent},` в твоем случае

2018-09-18 08:51 UTC, e-tolpeko requested changes

2018-09-18 08:51 UTC, e-tolpeko commented on src/app/app.component.ts
>    private ngUnsubscribe$ = new Subject();
сначала объявляются публичные переменные, затем protected, а потом уже private

2018-09-18 08:51 UTC, e-tolpeko commented on src/app/search-stream/search-stream.component.ts
> +    changeDetection: ChangeDetectionStrategy.OnPush
расставь правильно пробелы и отступы ctrl+alt+l . И так по всему проекту

2018-09-20 14:39 UTC, e-tolpeko requested changes

2018-09-20 14:39 UTC, e-tolpeko commented on src/app/app.module.ts
>    providers: [],
Удали если нету провайдеров

2018-09-20 14:39 UTC, e-tolpeko commented on src/app/core/core-routing.module.ts
> +    path: '',
такой роут в конце пишется

2018-09-20 14:39 UTC, e-tolpeko commented on src/app/core/header/header.component.ts
> +        if (!!value) {
переверни if

2018-09-20 14:39 UTC, e-tolpeko commented on src/app/main/main-routing.module.ts
> +  {path: '', redirectTo: '/games', pathMatch: 'full'},
пустой путь в конце пишется

2018-09-25 19:42 UTC, e-tolpeko approved these changes

2018-09-26 06:24 UTC, merged